name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Extract Zip File
      run: |
        unzip -o t999.zip
        # Agar files kisi andar wale folder mein extract hui hon to unhe bahar le aao
        if [ ! -f "gradlew" ]; then
          find . -maxdepth 2 -name "gradlew" -exec cp -r $(dirname {})/. . \;
        fi

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Remove signingConfig
      run: |
        find . -name "build.gradle.kts" -exec sed -i '/signingConfig =/d' {} + || true

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew || true

    - name: Build with Gradle
      run: ./gradlew assembleDebug --no-daemon

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: "**/build/outputs/apk/debug/*.apk"
        
